"""phase 4 transcript segments

Revision ID: 9595703e3906
Revises: 84bc6c9a40b5
Create Date: 2026-09-20 10:08:59.929228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9595703e3906'
down_revision: Union[str, None] = '84bc6c9a40b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('speaker_label', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sequence', name='uq_segment_meeting_sequence')
    )
    op.create_index('ix_segment_meeting_sequence', 'transcript_segments', ['meeting_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_transcript_segments_meeting_id'), 'transcript_segments', ['meeting_id'], unique=False)
    op.create_unique_constraint('uq_job_meeting_type', 'jobs', ['meeting_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_meeting_type', 'jobs', type_='unique')
    op.drop_index(op.f('ix_transcript_segments_meeting_id'), table_name='transcript_segments')
    op.drop_index('ix_segment_meeting_sequence', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    # ### end Alembic commands ###
